# Generated by Django 5.2.3 on 2025-08-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['business__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='uniq_branch_name_per_business'),
        ),
    ]
