# Generated by Django 5.2.3 on 2025-09-07 02:48

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_branch_options_alter_business_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedulePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(default=datetime.time(9, 0))),
                ('time_out', models.TimeField(default=datetime.time(18, 0))),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0)),
                ('break_hours', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('min_hours_required', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Minimum working hours to be considered present', max_digits=4)),
                ('is_flexible', models.BooleanField(default=False)),
                ('regular_work_days', models.CharField(default='0,1,2,3,4', help_text='Comma-separated weekdays: 0=Mon, 6=Sun', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='organization.branch')),
            ],
            options={
                'verbose_name': 'Work Schedule Policy',
                'verbose_name_plural': 'Work Schedule Policies',
                'ordering': ['branch__business__name', 'branch__name'],
            },
        ),
    ]
