# Generated by Django 5.2.3 on 2025-06-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_workschedulepolicy_delete_timelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('type', models.CharField(choices=[('REGULAR', 'Regular Holiday'), ('SPECIAL', 'Special Non-Working Holiday')], max_length=10)),
                ('is_national', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('undertime_minutes', models.PositiveIntegerField(default=0)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('holiday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timekeeping.holiday')),
            ],
        ),
    ]
