# Generated by Django 5.2.3 on 2025-06-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_workschedulepolicy_delete_timelog'),
        ('organization', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payroll_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('1st_half', 'First Half'), ('2nd_half', 'Second Half')], default='monthly', help_text='Indicates the payroll cycle: full month or split', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('employee', 'month', 'component', 'payroll_cycle')},
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cycle_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMI_1', 'Semi-Monthly 1st Half'), ('SEMI_2', 'Semi-Monthly 2nd Half')], max_length=10)),
                ('start_day', models.PositiveSmallIntegerField()),
                ('end_day', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_cycles', to='organization.business')),
            ],
            options={
                'unique_together': {('business', 'cycle_type')},
            },
        ),
    ]
