# Generated by Django 5.2.3 on 2025-06-28 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('payroll', '0002_alter_payrollrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=0)),
                ('standard_working_days', models.DecimalField(decimal_places=2, default=22, max_digits=5)),
                ('late_penalty_per_minute', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('undertime_penalty_per_minute', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('absent_penalty_per_day', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('ot_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=4)),
                ('rest_day_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=4)),
                ('holiday_regular_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('holiday_special_multiplier', models.DecimalField(decimal_places=2, default=1.3, max_digits=4)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_policy', to='organization.business')),
            ],
        ),
    ]
