# Generated by Django 5.2.3 on 2025-08-09 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_position'),
        ('payroll', '0003_payrollpolicy'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='positions.position'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
