# Generated by Django 5.2.3 on 2025-08-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('payroll', '0004_alter_salarystructure_position_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecord',
            name='payroll_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('SEMI_1', 'Semi-Monthly 1st Half'), ('SEMI_2', 'Semi-Monthly 2nd Half')], default='MONTHLY', help_text='Indicates the payroll cycle: full month or split', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='payrollcycle',
            constraint=models.UniqueConstraint(fields=('business', 'cycle_type'), name='uniq_business_cycle_type'),
        ),
    ]
