# Generated by Django 5.2.3 on 2025-08-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_payrollrecord_payroll_cycle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollcycle',
            unique_together=set(),
        ),
    ]
