# Generated by Django 5.2.3 on 2025-08-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_options'),
        ('organization', '0002_alter_branch_options_alter_business_options_and_more'),
        ('payroll', '0006_alter_payrollcycle_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecord',
            name='payroll_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='payroll.payrollcycle'),
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month being processed')),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='organization.business')),
                ('payroll_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payrollcycle')),
            ],
            options={
                'unique_together': {('business', 'month', 'payroll_cycle')},
            },
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_rates', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
