# Generated by Django 5.2.3 on 2025-06-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_timelog'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedulePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(default='09:00')),
                ('time_out', models.TimeField(default='17:00')),
                ('break_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('min_hours_required', models.DecimalField(decimal_places=2, default=4.0, help_text='Minimum working hours to be considered present', max_digits=4)),
                ('is_flexible', models.BooleanField(default=False)),
                ('regular_work_days', models.CharField(default='0,1,2,3,4', help_text='Comma-separated weekdays: 0=Mon, 6=Sun', max_length=20)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedule', to='organization.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
