# Generated by Django 5.2.3 on 2025-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_workschedulepolicy_delete_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedulepolicy',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
