# Generated by Django 5.2.3 on 2025-08-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
