# Generated by Django 5.2.3 on 2025-09-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkSchedulePolicy',
        ),
    ]
